### ISSUE TITLE
Registering Template

### ISSUE THREAD

**Issue by Joliciel** [RobertArtigas/DEVUNA__IDE__#1]
Hi Roberto,

You have done a great webinar yesterday regarding the redirection of projects and the use of KSS. A wonderful job, a great idea to separate the environment when we only need to work on specific classes and templates for a particular application. I've been using ABCClassViewer for the pass 15 years initially it was through Keystone couple of years after the KSS came along. These two tools are very useful.  Couple years ago when I found Randy Rodgers has made ABCClassViewer, KSS and other tools available. At first it was not so obvious to understand how to get around. I'm glad some of the Clarion developers as you and Mark Riffey has come up with a way to work these wonderful tools. What makes interesting is the fact that we have to create a separate redirection that will only use the needed classes and template for a specific application. This is a good idea. I'm having some issues to implement, though. I'll explain step by step what I went through.

1. Creating the same structure as yours with the following C:\_GIT_\Devuna\_IDE_
2. Decompressing the Devuna files from your zip under the _IDE_ directory
3. Modifying C:\_GIT_\Devuna\_IDE_\BIN\Clarion110.RED according to RobertoArtigas.RED up to --IGNORE WHAT COMES AFTER THIS-
4. Open Clarion Options under version by adding the Directory scanned for ABC Classes to C:\_GIT_\Devuna\_IDE_\LibSrc\Win 
5. Regarding the macros reddir and root do we need to change 
from 
reddir: c:\Clarion11\BIN
root: C:\Clarion11
TO
reddir: C:\_GIT_\Devuna\_IDE_\BIN
root: C:\_GIT_\Devuna\_IDE_
6. I believe in the template registry it needs to be empty. We only need to register the Devuna template from.
C:\_GIT_\Devuna\_IDE_\Template\win. When I make the following errors occur.
TPL: (KCR_ABBROWSE.TPW 30,1) Error: Unknown template type Window(ABC) - using ToDo - C:\_GIT_\Devuna\_IDE_\Template\win\KCR_ABBROWSE.TPW:30
TPL: (KCR_ABBROWSE.TPW 69,77) Error: Value of parameters has incorrect type - C:\_GIT_\Devuna\_IDE_\Template\win\KCR_ABBROWSE.TPW:69,77
TPL: (KCR_ABBROWSE.TPW 2626,66) Error: Expected a statement - C:\_GIT_\Devuna\_IDE_\Template\win\KCR_ABBROWSE.TPW:2626,66
TPL: (KCR_ABBROWSE.TPW 2626,66) Error: ) expected - C:\_GIT_\Devuna\_IDE_\Template\win\KCR_ABBROWSE.TPW:2626,66
TPL: (KCR_ABBROWSE.TPW 2626,66) Error: Unknown property PROP:DropWidth - C:\_GIT_\Devuna\_IDE_\Template\win\KCR_ABBROWSE.TPW:2626,66
TPL: (KCR_ABBROWSE.TPW 3018,114) Error: Expected a statement - C:\_GIT_\Devuna\_IDE_\Template\win\KCR_ABBROWSE.TPW:3018,114
TPL: (KCR_ABBROWSE.TPW 3018,114) Error: ) expected - C:\_GIT_\Devuna\_IDE_\Template\win\KCR_ABBROWSE.TPW:3018,114
TPL: (KCR_ABBROWSE.TPW 3018,114) Error: Unknown property PROP:DropWidth - C:\_GIT_\Devuna\_IDE_\Template\win\KCR_ABBROWSE.TPW:3018,114
TPL: (KCR_ABBROWSE.TPW 3079,64) Error: Expected a statement - C:\_GIT_\Devuna\_IDE_\Template\win\KCR_ABBROWSE.TPW:3079,64
TPL: (KCR_ABBROWSE.TPW 3079,64) Error: ) expected - C:\_GIT_\Devuna\_IDE_\Template\win\KCR_ABBROWSE.TPW:3079,64
TPL: (KCR_ABBROWSE.TPW 3079,64) Error: Unknown property PROP:DropWidth - C:\_GIT_\Devuna\_IDE_\Template\win\KCR_ABBROWSE.TPW:3079,64
TPL: (KCRCNTRL.TPW 384,114) Error: Value of parameter has incorrect type - C:\_GIT_\Devuna\_IDE_\Template\win\KCRCNTRL.TPW:384,114
TPL: (KCRQEIP.TPW 28,90) Error: Value of parameter has incorrect type - C:\_GIT_\Devuna\_IDE_\Template\win\KCRQEIP.TPW:28,90
TPL: (KCRQEIP.TPW 29,39) Error: Value of parameter has incorrect type - C:\_GIT_\Devuna\_IDE_\Template\win\KCRQEIP.TPW:29,39
TPL: (KCRQEIP.TPW 30,37) Error: Value of parameter has incorrect type - C:\_GIT_\Devuna\_IDE_\Template\win\KCRQEIP.TPW:30,37
TPL: (KCRQEIP.TPW 31,39) Error: Value of parameter has incorrect type - C:\_GIT_\Devuna\_IDE_\Template\win\KCRQEIP.TPW:31,39

I'm at this point 
What do I need to do from there?

Thank you Roberto and have a great day,
Robert

**Comment by RobertArtigas** [comment]
Greetings - My apologies
Just register the additional templates in the directory they are located.
The RED file should pick them up if you have the entry pointing to the
location
Will add that to the instructions to the help.
Thank you for letting me know.
Regards,
Roberto Artigas

**Comment by Joliciel** [comment]
Hi Robert,

Appreciate your response I was able to register the templates and compile Kss and Autoshotdown without error. For the ABCview application, while compiling I have the following error 
file not found or cannot be open: abcview.res - C:\_GIT_\Devuna\__IDE__\Application\ClassViewer\source\abcview.MAP:1
What do I need to do to correct this error?

To let you know regarding the needed template set, aside from Clarion and Devuna, we need to register templates from Capesoft and Icetips.  The templates in question are StoreCompileDateInVariable from Icetips Utility,  EnableWinEvent,  StringTheory and ActivexFiles from Capesoft.  I was  able to register StringTheory and ActivexFiles the others not, I do not have a licence of those templates. Are they required? Also I had some compilation error in Kss at first for which I was able to rectifying it.  Here's the error
Unknown identifier: KEY_QUERY_VALUE - C:\_GIT_\Devuna\__IDE__\Application\kss\source\kss015.clw:87,62
Unknown identifier: REG_OPTION_NON_VOLATILE - C:\_GIT_\Devuna\__IDE__\Application\kss\source\kss015.clw:116,69
Unknown identifier: KEY_ALL_ACCESS - C:\_GIT_\Devuna\__IDE__\Application\kss\source\kss015.clw:116,93
Unknown identifier: KEY_QUERY_VALUE - C:\_GIT_\Devuna\__IDE__\Application\kss\source\kss015.clw:121,68
Unknown identifier: KEY_SET_VALUE - C:\_GIT_\Devuna\__IDE__\Application\kss\source\kss015.clw:401,65
Label duplicated, second used: _XFILES_ - C:\Clarion11\Accessory\libsrc\win\xfiles.inc:7
Label duplicated, second used: _XFILES_ - C:\Clarion11\Accessory\libsrc\win\xfiles.inc:7
Label duplicated, second used: _XFILES_ - C:\Clarion11\Accessory\libsrc\win\xfiles.inc:7

To correct the error the EQUATES were commented in Kss.clw file I've removed the comment 
the duplication with _XFILES_ I have erased the symbol from Kss.cwproj since the equate _XFILES_ is also found in xFiles.inc . Then I was able to compile the applications without error. Is there any reason why the EQUATES were commented and why the _XFiles_ were used as a symbol instead the equate from xFile.inc?


Thank you
Robert

**Comment by mriffey** [comment]
The icetips template should be removed. I included it inadvertently. The use of "VersionMe" takes care of this functionality.

**Comment by mriffey** [comment]
>  Is there any reason why the EQUATES were commented and why the XFiles were used as a symbol instead the equate from xFile.inc?

The equates were duplicated elsewhere in my IDE. The xfiles.inc issue was a mistake that could probably be resolved by using ,ONCE on the include (assuming I didnt use it already). xfiles.inc in the project can also be de-duped if the project properties for that file are changed to "NONE" instead of "COMPILE" - though I dont recall if they were set that way.

**Comment by RobertArtigas** [comment]
Greetings -

I have updated the DEVUNA GitHub documentation. If you have not looked at
it, there is a new IMPORTANT item to read.
Please, from now on, send any additional questions to the email that is
shown in the GitHub directory.

You can also ask questions in the SKYPE clarion newsgroups. There are more
experience individuals about environments there.
I will answer there if I can, and you will get better
question/answers/diagnosis from other folks that regularly work on these
utilities.
That is probably a better option, since the more eyes can look at a
problem, the faster you will get a possible answer.

I will answer what I can, and as the documentation clearly states, *you*
will have to solve the problems with any conflicts with *your* environment.

I do not know every answer about how YOU have things set up. I can make
some guesses. You get to do some of your own figuring out about YOUR
environment.

What might make this easier for you, is to use your own RED file and make
the modifications you need, to include the separate directories. And that
is your choice.
In the webinar, I pointed out that I provided several RED files, and that
you would have to think about how to integrate the directories with your
environment.

I have both the Icetips and Capesoft templates registered in my
environment. However, AS FAR AS I KNOW, those might not be needed.
If they are NEEDED, that was a choice by the original author, and YOU will
have to resolve those items.

I am mostly aware about me getting it running on my environment. And I
provided my environment, and others, as  examples.
This is done to help others with the setup. It is provided free of charge.
And there is nothing simple about integrating different environments.
I do not recommend anything I do to anyone. And the environment I have
worked on has taken years and a lot of effort to get correct.

I have no idea about the Unknown Identifiers. Those are part of the
registry keyword items. They compile cleanly for various individuals.
I have no idea about the Duplicate XFILES labels. You will note in the
documentation I had to comment out a couple of labels myself.
Any questions about XFILES and why things are done there in any particular
way, you will have to direct to the author.

The MAP is something created when you compile and that is determined by
your RED environment.
It is looking for it in a place where it does not seem to exist. Look at
where another one of your projects want it.

That is part of the reason that I do not recommend my environment to
anyone. Lots of pieces to figure out.
The templates have to be registered where they are located. The RED has to
be modified for the classes and templates.
The order of the items might make a difference when you have duplicate
template sets in different directories.

Regards,
Roberto Artigas

**Comment by Joliciel** [comment]
Hi Robert and Mike,

Wow, thank you so much for your responses. I will join the group on SKYPE. Regarding the Clarion environment modification in the redirection RED file that I have to do, it will be done according to my need this is exactly what I’ll be doing. 

Thanks again
Robert

**Comment by Joliciel** [comment]
Hi Robert,

Regarding joining SKYPE Clarion newsgroups, I found ClarionLive and Clarionhub is there one of these groups or else?

Cordially,
Robert

**Comment by RobertArtigas** [comment]
Greetings -
SKYPE: 'Clarion Live', 'CW-Talk'
Clarion Hub: https://clarionhub.com/
Regards,
Roberto Artigas

**Comment by RobertArtigas** [comment]
All questions answered
